FROM node as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json .
RUN npm install
COPY . .
ARG REACT_APP_NOT_SECRET_CODE
ENV REACT_APP_NOT_SECRET_CODE=$REACT_APP_NOT_SECRET_CODE
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html