version: "3.9"
services:
 db:
    image: "postgres:14.5-alpine"
    restart: always
    container_name: postgresql-server
    hostname: postgresql-server
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=iab3302022
      - POSTGRES_DB=iab330nodered
