version: "3.9"
services:
 db:
    image: "sqlite"
    restart: always
    container_name: sqlite-server
    hostname: sqlite-server
    ports:
      - "5432:5432"
    volumes:
      - ./data/iab33
    environment:
      - SQLITE=dbuser
      - SQLITE_PASSWORD=iab3302022
      - SQLITE_DB=iab330
nodered: 
    image: nodered/node-red
    container_name: iab330nodered
    hostname: iab330nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
